In [2]:
# Getting mean
import numpy as np
i=np.array([1,82,3,6])


23.0

In [3]:
# Gives sum of all elements



92

In [4]:
# Sorts the array



array([ 1,  3,  6, 82])

In [5]:
# Splitting of an array into n arrays

x=np.array(([1,2,3,2,4,6,6,9,0,5,3]))


np.split(x,[2,5,7])

[array([1, 2]), array([3, 2, 4]), array([6, 6]), array([9, 0, 5, 3])]

In [6]:
# Coloumn-wise split

x=np.array(([1,2,3,5,7,9,3],
            [2,4,6,8,10,12,14]))



[array([[1, 2],
        [2, 4]]),
 array([[ 3,  5,  7],
        [ 6,  8, 10]]),
 array([[ 9,  3],
        [12, 14]])]

In [7]:
# Row-wise split

x=np.array(([1,2,3,5,7,9,3],
            [2,4,6,8,10,12,14]))



[array([[ 1,  2,  3,  5,  7,  9,  3],
        [ 2,  4,  6,  8, 10, 12, 14]]),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32)]

In [ ]:
""" Create a Python script that utilizes NumPy to simulate dice rolls,
calculate probabilities, and perform basic statistical analysis.
This project aims to demonstrate the use of NumPy for simulations and basic statistical computations"""
#this one is optional but it combines your skills on python and numpy you may also use visualization 